l_braz_por:
 pse_power_main_botton_effect_covenant_composer_desc:1000 "\n§EEffects to Empire:§!\n$MOD_POP_GROWTH_SPEED$: §G+20%§!\n$MOD_LEADER_AGE$: §G+20§! Years$pse_power_main_botton_click_tooltip$"
